# Generated by Django 5.2.6 on 2025-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studentclass',
            old_name='streamname',
            new_name='streamName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentclass',
            name='yearStream',
            field=models.CharField(max_length=100),
        ),
    ]
